### PR TITLE
Remove SafetyLaser State from fetch_msgs

### PR DESCRIPTION
**Pull request by cjds**
As this message only applies to some robots, this should be removed

### CODE REVIEW

**Comment by cjds** [comment]
@rctoris @chadrockey

**Comment by chadrockey** [comment]
@cjds For the robots that do use it, can you slack me where the replacement for this message is?

**Comment by moriarty** [comment]
@cjds did you test this against the new `fetch_binary_driver` ? this msg was originally in the drivers, then moved here, then moved into an private msgs repository...

**Review by moriarty — CHANGES_REQUESTED** [review]
You didn't remove it from the CMakeLists.txt, so I also suspect it wasn't tested.

**Comment by moriarty** [comment]
@cjds I'm preparing a release for melodic, should this PR go in?

**Comment by erelson** [comment]
@cjds What should we do with this? :)

**Comment by cjds** [comment]
I'm fine with merging this. This is not used in any public driver

**Comment by mikeferguson** [comment]
@erelson pretty sure this will break your build - since CMakeLists.txt still refers to the message

**Comment by erelson** [comment]
Yup. :(

**Comment by erelson** [comment]
Amended with https://github.com/fetchrobotics/fetch_msgs/commit/c2df663c133c4b4d61071d061f41ca583fbdcea5

**Pull request merged**
